// The SDK's layouts (src/idl-layout.ts, generated by `npm run sync-idl`) must match the program's
// committed IDL (programs/anyfee/idl/anyfee.json) and the copy shipped in sdk/src/idl/. Fails when
// the program changed its IDL and the SDK was not re-synced.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  ACCOUNTS,
  EVENTS,
  INSTRUCTIONS,
  PROGRAM_ERRORS,
  PROGRAM_ID,
  accountDiscriminator,
  eventDiscriminator,
  instructionDiscriminator,
  type ArgType,
} from "../src/index.ts";

const root = fileURLToPath(new URL("../../", import.meta.url));
// target/ is a local, gitignored build output and may be ahead of the committed IDL; not checked.
const sources = ["sdk/src/idl/anyfee.json", "programs/anyfee/idl/anyfee.json"].filter((p) => existsSync(root + p));

interface IdlAccountItem {
  name: string;
  writable?: boolean;
  signer?: boolean;
  optional?: boolean;
  address?: string;
  accounts?: IdlAccountItem[];
}
type IdlType = string | { option?: IdlType };
interface Idl {
  address?: string;
  instructions: { name: string; discriminator?: number[]; accounts: IdlAccountItem[]; args: { name: string; type: IdlType }[] }[];
  accounts?: { name: string; discriminator?: number[] }[];
  events?: { name: string; discriminator?: number[] }[];
  errors?: { code: number; name: string; msg?: string }[];
  types?: { name: string; type: { kind: string; fields?: { name: string; type: IdlType }[] } }[];
}

const norm = (t: IdlType | ArgType): string => {
  if (typeof t === "string") return t === "publicKey" ? "pubkey" : t;
  if ("option" in t && t.option !== undefined) return `option<${norm(t.option as IdlType)}>`;
  return JSON.stringify(t);
};
const flatten = (items: IdlAccountItem[]): IdlAccountItem[] => items.flatMap((a) => (a.accounts ? flatten(a.accounts) : [a]));
type Row = { name: string; writable: boolean; signer: boolean; optional: boolean; address: string | null };

if (sources.length === 0) {
  test("IDL conformance (skipped: no IDL in the repo yet — build the program, then `npm run sync-idl`)", { skip: true }, () => {});
}

for (const src of sources) {
  const idl = JSON.parse(readFileSync(root + src, "utf8")) as Idl;

  test(`[${src}] program address`, () => {
    assert.equal(idl.address, PROGRAM_ID.toBase58());
  });

  test(`[${src}] same instruction set`, () => {
    assert.deepEqual(Object.keys(INSTRUCTIONS).sort(), idl.instructions.map((i) => i.name).sort(), "run `npm run sync-idl -w @anyfee/sdk`");
  });

  test(`[${src}] instructions: discriminators, accounts, args`, () => {
    for (const ix of idl.instructions) {
      const ours = (INSTRUCTIONS as Record<string, (typeof INSTRUCTIONS)[keyof typeof INSTRUCTIONS]>)[ix.name];
      assert.ok(ours, `SDK has no layout for ${ix.name}`);
      if (ix.discriminator) assert.deepEqual(Array.from(instructionDiscriminator(ix.name)), ix.discriminator, `${ix.name}: discriminator`);
      const theirs: Row[] = flatten(ix.accounts).map((a) => ({
        name: a.name,
        writable: !!a.writable,
        signer: !!a.signer,
        optional: !!a.optional,
        address: a.address ?? null,
      }));
      const mine: Row[] = ours.accounts.map((a) => ({
        name: a.name,
        writable: "writable" in a && !!a.writable,
        signer: "signer" in a && !!a.signer,
        optional: "optional" in a && !!a.optional,
        address: ("address" in a && a.address) || null,
      }));
      assert.deepEqual(mine, theirs, `${ix.name}: accounts differ`);
      assert.deepEqual(
        ours.args.map((a) => ({ name: a.name, type: norm(a.type) })),
        ix.args.map((a) => ({ name: a.name, type: norm(a.type) })),
        `${ix.name}: args differ`,
      );
    }
  });

  test(`[${src}] accounts and events: discriminators and fields`, () => {
    const check = (kind: "account" | "event", name: string, disc: number[] | undefined, fields: readonly { name: string; type: string }[]) => {
      const expected = kind === "account" ? accountDiscriminator(name) : eventDiscriminator(name);
      if (disc) assert.deepEqual(Array.from(expected), disc, `${kind} ${name}: discriminator`);
      const ty = idl.types?.find((t) => t.name === name);
      assert.ok(ty?.type.fields, `IDL has no struct type ${name}`);
      assert.deepEqual(
        fields.map((f) => ({ name: f.name, type: f.type })),
        ty.type.fields.map((f) => ({ name: f.name, type: norm(f.type) })),
        `${kind} ${name}: fields differ`,
      );
    };
    assert.deepEqual(Object.keys(ACCOUNTS).sort(), (idl.accounts ?? []).map((a) => a.name).sort());
    for (const a of idl.accounts ?? []) check("account", a.name, a.discriminator, (ACCOUNTS as Record<string, { fields: readonly { name: string; type: string }[] }>)[a.name]!.fields);
    assert.deepEqual(Object.keys(EVENTS).sort(), (idl.events ?? []).map((e) => e.name).sort());
    for (const e of idl.events ?? []) check("event", e.name, e.discriminator, (EVENTS as Record<string, { fields: readonly { name: string; type: string }[] }>)[e.name]!.fields);
  });

  test(`[${src}] error codes`, () => {
    assert.deepEqual(
      Object.entries(PROGRAM_ERRORS).map(([code, e]) => ({ code: Number(code), name: e.name, msg: e.msg })),
      (idl.errors ?? []).map((e) => ({ code: e.code, name: e.name, msg: e.msg ?? e.name })),
    );
  });
}
