// Syncs the SDK with the program's Anchor IDL:
//   1. copies programs/anyfee/idl/anyfee.json (committed by the program) — or target/idl/anyfee.json —
//      to sdk/src/idl/anyfee.json (shipped as "@anyfee/sdk/idl"),
//   2. regenerates sdk/src/idl-layout.ts (instruction/account/event layouts + error codes) that the
//      builders and decoders use.
// Usage: npm run sync-idl -w @anyfee/sdk   (then: npm test -w @anyfee/sdk)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));
const sources = process.argv[2] ? [process.argv[2]] : ["programs/anyfee/idl/anyfee.json", "target/idl/anyfee.json"];
const src = sources.find((p) => existsSync(p.startsWith("/") ? p : root + p));
if (!src) {
  console.error(`No IDL found (looked for ${sources.join(", ")}). Build the program first.`);
  process.exit(1);
}
const raw = readFileSync(src.startsWith("/") ? src : root + src, "utf8");

type IdlType = string | { option: IdlType };
interface IdlAccount {
  name: string;
  writable?: boolean;
  signer?: boolean;
  optional?: boolean;
  address?: string;
  accounts?: IdlAccount[];
}
interface Idl {
  address: string;
  instructions: { name: string; accounts: IdlAccount[]; args: { name: string; type: IdlType }[] }[];
  accounts?: { name: string }[];
  events?: { name: string }[];
  errors?: { code: number; name: string; msg?: string }[];
  types?: { name: string; type: { kind: string; fields?: { name: string; type: IdlType }[] } }[];
}
const idl = JSON.parse(raw) as Idl;

const flat = (xs: IdlAccount[]): IdlAccount[] => xs.flatMap((a) => (a.accounts ? flat(a.accounts) : [a]));
const ty = (t: IdlType): string => (typeof t === "string" ? JSON.stringify(t === "publicKey" ? "pubkey" : t) : `{ option: ${ty(t.option)} }`);
const fields = (name: string) => {
  const t = idl.types?.find((x) => x.name === name);
  if (!t?.type.fields) throw new Error(`IDL has no struct ${name}`);
  return t.type.fields
    .map((f) => {
      if (typeof f.type !== "string") throw new Error(`${name}.${f.name}: unsupported field type ${JSON.stringify(f.type)}`);
      return `      { name: ${JSON.stringify(f.name)}, type: ${ty(f.type)} },`;
    })
    .join("\n");
};

const ixs = idl.instructions
  .map((ix) => {
    const accs = flat(ix.accounts)
      .map((a) => {
        const parts = [`name: ${JSON.stringify(a.name)}`];
        if (a.writable) parts.push("writable: true");
        if (a.signer) parts.push("signer: true");
        if (a.optional) parts.push("optional: true");
        if (a.address) parts.push(`address: ${JSON.stringify(a.address)}`);
        return `      { ${parts.join(", ")} },`;
      })
      .join("\n");
    const args = ix.args.map((a) => `      { name: ${JSON.stringify(a.name)}, type: ${ty(a.type)} },`).join("\n");
    return `  ${ix.name}: {\n    name: ${JSON.stringify(ix.name)},\n    accounts: [\n${accs}\n    ],\n    args: [\n${args}\n    ],\n  },`;
  })
  .join("\n");

const accounts = (idl.accounts ?? []).map((a) => `  ${a.name}: {\n    name: ${JSON.stringify(a.name)},\n    fields: [\n${fields(a.name)}\n    ],\n  },`).join("\n");
const events = (idl.events ?? []).map((e) => `  ${e.name}: {\n    name: ${JSON.stringify(e.name)},\n    fields: [\n${fields(e.name)}\n    ],\n  },`).join("\n");
const errors = (idl.errors ?? []).map((e) => `  ${e.code}: { name: ${JSON.stringify(e.name)}, msg: ${JSON.stringify(e.msg ?? e.name)} },`).join("\n");

const out = `// GENERATED by sdk/scripts/sync-idl.ts from ${src} — do not edit by hand.
// Re-run \`npm run sync-idl -w @anyfee/sdk\` whenever the program's IDL changes.
import type { AccountDataLayout, InstructionLayout } from "./layout-types.ts";

export const IDL_PROGRAM_ADDRESS = ${JSON.stringify(idl.address)};

export const INSTRUCTIONS = {
${ixs}
} as const satisfies Record<string, InstructionLayout>;

export const ACCOUNTS = {
${accounts}
} as const satisfies Record<string, AccountDataLayout>;

export const EVENTS = {
${events}
} as const satisfies Record<string, AccountDataLayout>;

/** Custom program errors (Anchor codes start at 6000). */
export const PROGRAM_ERRORS: Record<number, { name: string; msg: string }> = {
${errors}
};
`;

mkdirSync(fileURLToPath(new URL("../src/idl/", import.meta.url)), { recursive: true });
writeFileSync(fileURLToPath(new URL("../src/idl/anyfee.json", import.meta.url)), raw);
writeFileSync(fileURLToPath(new URL("../src/idl-layout.ts", import.meta.url)), out);
console.log(`synced ${src} -> sdk/src/idl/anyfee.json + sdk/src/idl-layout.ts (${idl.instructions.length} instructions, ${idl.events?.length ?? 0} events, ${idl.errors?.length ?? 0} errors)`);
